version: 2

sources:
  - name: crypto_raw
    schema: crypto_raw
    # it defines raw database tables

    tables:
      - name: daily_prices
        description: The daily info table for the crytpo currencies
        # description belong to daily_prices


